### ISSUE TITLE
Olive IMU noise issue.

### ISSUE THREAD

**Issue by J1NJO** [olive-robotics/olvx_playground_imu#2]
Hey, I am using Olive IMU for a Visual based localization and mapping in maritime scenarios. So I have recorded the data for it with olive IMU mounted on a boat/vessel. Below the plots of IMU acceleration recorded for over 15mins. 

![imu_accln](https://github.com/olive-robotics/olv_imu_playground_cpp/assets/115921687/5b41dc16-74e6-409b-bd50-c123fccffeec)

![imu_accln_1](https://github.com/olive-robotics/olv_imu_playground_cpp/assets/115921687/b6414a51-4b4e-416b-991d-e84abe393b9f)
  
Firstly, noise here is very much comparable to the reading of IMU in x and y. Noise band seems to be having a width of ~0.3-0.4 m/s2. How much noise is expected from the olive IMU? To me this seems a lot higher on noise side.  

Secondly, acceleration in y seems to have bias of ~0.25m/s2.  

What do you make of this results? And how can I improve it?

**Comment by cxdcxd** [comment]
@J1NJO Thanks for your message. 

One thing you can try is to call the /setBias service. It will collect samples and will remove the bias. 

https://docs.olive-robotics.com/hardware/imu/OLVX%E2%84%A2-IMU01-9D_10x.html#services

![image](https://github.com/olive-robotics/olv_imu_playground_cpp/assets/5897501/7631d970-678f-44c8-b5b7-16a64caa27ca)

For the noise reduction, we will update a new software patch soon, which you can change some internal lowlevel parameters to make it compatible more for your application.
